# Generated by Django 5.1.1 on 2024-09-28 11:47

import django.core.validators
import petstagram.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='First name should be at least 2 letters long.'), petstagram.accounts.validators.IsAlphaValidator(message='First name should consist of only letters.')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='Last name should be at least 2 letters long.'), petstagram.accounts.validators.IsAlphaValidator(message='Last name should consist of only letters.')])),
                ('profile_picture', models.URLField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do Not Show')])),
            ],
        ),
    ]
