# Generated by Django 5.1.1 on 2024-09-28 11:56

import django.core.validators
import petstagram.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2, message='First name should be at least 2 letters long.'), petstagram.accounts.validators.IsAlphaValidator(message='First name should consist of only letters.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do Not Show')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Last name should be at least 2 letters long.'), petstagram.accounts.validators.IsAlphaValidator(message='Last name should consist of only letters.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
