# Generated by Django 5.1.2 on 2024-10-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, null=True, unique=True),
        ),
    ]
